version: '3.8'
services:
  db:
    image: mysql:latest
    networks:
      - db_django
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: 'sholex'
    secrets:
      - db_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.type==db'
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 30s
        delay: 10s
      update_config:
        parallelism: 1
        delay: 20s
        order: stop-first
        failure_action: rollback
        monitor: 15s
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
    configs:
      - source: mysql
        target: /etc/mysql/conf.d/my.cnf
  lilsholex:
    image: docker.pkg.github.com/sholex-team/lilsholex/lilsholex:latest
    networks:
      - db_django
      - django_nginx
    volumes:
      - groupguard:/home/sholex/groupguard/migrations
      - persianmeme:/home/sholex/persianmeme/migrations
      - support:/home/sholex/support/migrations
      - anonymous:/home/sholex/anonymous/migrations
    depends_on:
      - db
    secrets:
      - db_password
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        monitor: 20s
        failure_action: rollback
      restart_policy:
        max_attempts: 3
        delay: 5s
        condition: on-failure
        window: 30s
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
        failure_action: pause
    healthcheck:
      test: 'python check_process.py'
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

  web:
    image: docker.pkg.github.com/sholex-team/lilsholex/nginx:latest
    networks:
      - django_nginx
    depends_on:
      - django
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        monitor: 5s
        failure_action: rollback
      restart_policy:
        max_attempts: 2
        delay: 10s
        window: 5s
        condition: on-failure
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        order: start-first
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
networks:
  db_django:
    driver: 'overlay'
    name: 'db_django'
  django_nginx:
    driver: 'overlay'
    name: 'django_nginx'
volumes:
  db:
    name: 'db'
  groupguard:
    name: 'groupguard'
  persianmeme:
    name: 'persianmeme'
  anonymous:
    name: 'anonymous'
  support:
    name: 'support'
secrets:
  db_password:
    external: true
  django:
    external: true
  anonymous:
    external: true
  group:
    external: true
  meme:
    external: true
  support:
    external: true
  admin:
    external: true
configs:
  nginx:
    file: nginx/sholex.conf
  mysql:
    file: mysql/my.cnf